sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    access-key-id: LTAI5tH3JT6xkZ4ZrHkhrqaY
    access-key-secret: q9KkSm7uQY6bjKbGQjvMNJH4ttcM2b
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: takeouttake

  redis:
    host: localhost
    port: 6379

  wechat:
    appid: wx7b5ab6886671d49e
    secret: f17e73b0f1912f8a8135a5df9d412b1e

